### ISSUE TITLE
dotnet restore --interactive does not work On prem

### ISSUE THREAD

**Issue by stephan7878** [microsoft/artifacts-credprovider#45]
**Environment**

- Using Ubuntu 18.04.1 LTS (Bionic Beaver) on a Windows host.
- Connecting to a TFS 2017 Update 2 Server.
- Installed latest Nuget.exe, .Net Core v2.1.6 (SDK 2.1.500)
- Installed Microsoft.NuGet.CredentialProvider and verified content in `$HOME\.nuget\plugins` 

**Issues**

- `dotnet restore --interactive` does not prompt
- `dotnet restore` with nuget.config file containing PAT token throws exception

```
/usr/share/dotnet/sdk/2.1.500/NuGet.targets(114,5): error : Unable to load the service index for source https://[REDACTED]/nuget/v3/index.json. [REDACTED]
/usr/share/dotnet/sdk/2.1.500/NuGet.targets(114,5): error :   GSSAPI operation failed with error - An invalid status code was supplied (Invalid value in argument). [REDACTED]
```

- `dotnet restore` without specifying PAT token in nuget.config throws exception

```
/usr/share/dotnet/sdk/2.1.500/NuGet.targets(114,5): error : Unable to load the service index for source https://REDACTED/nuget/v3/index.json. [REDACTED]
/usr/share/dotnet/sdk/2.1.500/NuGet.targets(114,5): error :   GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate). [REDACTED]
```

Please advise on any know issues / workaround to get a `dotnet restore` working against a TFS private package feed.

**Comment by stephan7878** [comment]
I've attempted the workaround described in [#6135](https://github.com/Microsoft/azure-pipelines-tasks/issues/6135#issuecomment-439272181), also without success.

**Comment by stephan7878** [comment]
Thanks @phil-hodgson. I created a `globals.json` to force .Net SDK 2.1.402, but still seeing the same behaviour.

**CredProvider**
```
export NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED=true
export VSS_NUGET_EXTERNAL_FEED_ENDPOINTS="{\"endpointCredentials\": [{\"endpoint\":\"https://[REDACTED]/nuget/v3/index.json\", \"username\":\"vsts\", \"password\":\"[PAT]\"}]}"
dotnet restore
```
Exception:
```
(Restore target) -> 
/usr/share/dotnet/sdk/2.1.402/NuGet.targets(114,5): error : Unable to load the service index for source https://[REDACTED]/nuget/v3/index.json. [REDACTED]
/usr/share/dotnet/sdk/2.1.402/NuGet.targets(114,5): error :   GSSAPI operation failed with error - An invalid status code was supplied (Invalid value in argument). [REDACTED]
```

**Using a nuget.config**
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="tfs" value="https://[REDACTED]/nuget/v3/index.json" />
  </packageSources>
  <disabledPackageSources />
  <packageSourceCredentials>
    <tfs> 
      <add key="Username" value="vsts" />
      <add key="ClearTextPassword" value="[PAT]" /> 
      <add key="ValidAuthenticationTypes" value="basic" /> 
    </tfs>
  </packageSourceCredentials>
</configuration>
```
Run restore
```
dotnet restore
```
Exception:
```
/usr/share/dotnet/sdk/2.1.402/NuGet.targets(114,5): error : Unable to load the service index for source https://[REDACTED]/nuget/v3/index.json. [REDACTED]
/usr/share/dotnet/sdk/2.1.402/NuGet.targets(114,5): error :   GSSAPI operation failed with error - An invalid status code was supplied (Invalid value in argument). [REDACTED]
```

I also upgrade to .NET SDK 2.2 also without success, but this is expected as per your link.

Any other ideas?

**Comment by moisoiu** [comment]
Hello, I'm having the same issue. 

I've tried also to restore from a Private TFS Package and having the same issue. 

Dockerfile

`FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
RUN apt-get update 
run apt-get install -y gss-ntlmssp
ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0

WORKDIR /src
COPY . .

RUN dir
COPY nuget.config ./
RUN dotnet restore "Web.csproj" --configfile nuget.config -nowarn:msb3202,nu1503 --verbosity diag

WORKDIR "/src/Web"
RUN dotnet build "Web.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Web.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Web.dll"]`

I've tried also with _ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0_
Exception is 401 Unauthorized 

If I remove _ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0_ I receive the same error as above. 

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <config>
    <add key="http_proxy" value="[redacted]" />
    <add key="http_proxy.user" value="username" />
    <add key="x_http_proxy.password" value="password" />
  </config>
 <packageSources>
    
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
	<add key="CIS" value="[redacted]/_packaging/[redacted]/nuget/v3/index.json" />
 </packageSources>
 <packageSourceCredentials>
    <CIS>
      <add key="Username" value="{username}" />      
      <add key="ClearTextPassword" value="{pat}" />
    </CIS>
  </packageSourceCredentials>
</configuration>
`

**Comment by alexmullans** [comment]
I'm going to close this due to inactivity. Please reopen if this issue is still occuring.

**Comment by moisoiu** [comment]
Hi @alexmullans could you guide me please for a documentation where I can implement dotnet restore --interactivice for CI/CD with restore nuggets from private TFS packager ? And also in automatic way, so we don't have the add the password every time or once a month 

Right now I'm facing the same issue like @stephan7878. My workaround which I don't agree with, and trying to change is that we are building and restore de packages in TFS Build (not docker) and after copy in the docker image.

**Comment by simondel** [comment]
@alexmullans It still isn't prompting for me with:
* Azure DevOps Server 2019 
* dotnet v2.2.203
* artifacts-credprovider v0.1.15
* OS: Windows Server 2012 R2

Manually setting the env variable `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` is working for me, but it's not user friendly as the dotnet documenation mentions the `--interactive` flag for this use case.

Could you reopen this issue?

**Comment by Mobrockers** [comment]
I have the same problem, dotnet restore --interactive does not trigger login for on-premise tfs/azure devops server nuget feeds. It does trigger for cloud azure devops nuget feeds.

Please advice. Is the credential provider actually supposed to work with on-premise tfs/azure devops? If not, how do we use on-premise nuget feeds with dotnet restore in a user friendly way (ie not putting a json object in environment variables)? And also could this be reflected in the docs somewhere if it is in fact not supported? I can't find any information on this.

**Comment by jvdenning** [comment]
Just to add - we have just found that SDK v2.2.203 has broken the --interactive function (for Azure Devops hosted feeds). Reverting to v2.2.202 and it works.

**Comment by shubham90** [comment]
Closing this issue due to inactivity.

**Comment by Mobrockers** [comment]
@shubham90 what do you mean closing due to inactivity? We are waiting for clarification on the credential helper working with azure devops on premise or not. There's been zero answer.

**Comment by shubham90** [comment]
@Mobrockers I apologize for closing this. I missed the fact that this issue is talking about on premise scenario. Hosted ones had a similar bug which got fixed with .NET sdks latest release. 

After a quick glance at the code, it looks like --interactive won't work with onprem because it looks for source patterns only which are meaningful for hosted urls. I will change the title of this issue to mention onprem and create an internal bug which fixes this issue. 

Meanwhile, the only solution today is to use the environment variable VSS_NUGET_EXTERNAL_FEED_ENDPOINTS to give source and credentials which triggers a separate code path. I am sorry for this inconvenience.

**Comment by totollygeek** [comment]
I am also experiencing issues with the provider, but I use it in a container.
Here is the setup:

**Docker image**: mcr.microsoft.com/dotnet/core/sdk:3.0-bionic (same behavior with 2.2-bionic)
**Install provider in Dockerfile**: `RUN bash /application/scripts/installcredprovider.sh`
**Pass Env Variable In Compose**:  
```
environment:
            - VSS_NUGET_EXTERNAL_FEED_ENDPOINTS=${VSS_JSON}
```

Calling `dotnet restore` inside the container (with or without --interactive) always throws:

> /usr/share/dotnet/sdk/3.0.100-preview8-013656/NuGet.targets(123,5): error : Unable to load the service index for source [REDACTED]. [/application/build/_build.csproj]
> /usr/share/dotnet/sdk/3.0.100-preview8-013656/NuGet.targets(123,5): error :   GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (SPNEGO cannot find mechanisms to negotiate). [/application/build/_build.csproj]

Can anyone give me a hint how to fix this?

**Comment by Mobrockers** [comment]
@shubham90 thank you for reopening and filing a bug internally!

**Comment by totollygeek** [comment]
With release of 3.0 this is still NOT working for us. Nothing helps. Our whole Integration Test environment is halted due to this issue. I cannot make dotnet restore work on linux containers with our internal NuGet repository, no matter what. Please give me something. I don't want to switch to Windows containers...

**Comment by moisoiu** [comment]
Hello, for whos having this problem, maybe you can try this solution -> https://github.com/microsoft/artifacts-credprovider/issues/63

**Comment by totollygeek** [comment]
> 
> 
> Hello, for whos having this problem, maybe you can try this solution -> #63

OMG, THAT WORKED! Weeks have been lost, until this moment. Thank you so much!!!!

**Comment by kconfesor** [comment]
@totollygeek specifically worked for you, i'm still having the same issue :(

**Comment by Etheryte** [comment]
For anyone looking for a [summarized solution](https://www.karltarvas.com/2019/10/28/macos-restore-from-remote-nuget.html), here's what worked on a Mac setup:  

 1. generate a [personal acess token (PAT)](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops) that gives you rights to the given service;
 2. configure your `Nuget.config` to use the PAT for authentication using `Basic` auth as shown by [stephan7878](https://github.com/Microsoft/artifacts-credprovider/issues/45#issuecomment-446601574):  

    <pre>
    &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    &lt;configuration&gt;
        &lt;packageSources&gt;
            &lt;add key=&quot;NuGet official package source&quot; value=&quot;https://api.nuget.org/v3/index.json&quot; /&gt;
            &lt;add key=&quot;Partner&quot; value=&quot;https://tfs.partner.com/DefaultCollection/_packaging/Nuget/nuget/v3/index.json&quot; /&gt;
        &lt;/packageSources&gt;
        &lt;packageSourceCredentials&gt;
            &lt;Partner&gt; 
                &lt;add key=&quot;Username&quot; value=&quot;USERNAME&quot; /&gt;
                &lt;add key=&quot;ClearTextPassword&quot; value=&quot;PATSTRING&quot; /&gt;
                &lt;add key=&quot;ValidAuthenticationTypes&quot; value=&quot;basic&quot; /&gt; 
            &lt;/Partner&gt;
        &lt;/packageSourceCredentials&gt;
    &lt;/configuration&gt;
    </pre>

 3. clear the cache and restore the packages using [the old HTTP client](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-3.0#remarks):

    <pre>
    cd repo
    nuget locals -clear all && export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0 && nuget restore
    </pre>

**Comment by ming-tsai** [comment]
With have same error with dotnet sdk 3.1.200, any new information?

**Comment by herenhuang** [comment]
This appears to be resolved as per the comments. Please let us know if this is still an existing issue!

**Comment by Mobrockers** [comment]
@herenhuang No I don't think the actual original problem has been solved, everything here so far has been a workaround using non-interactive authentication.

The actual issue is that **interactive** login doesn't work on-premises.

As you can see in this post: https://github.com/microsoft/artifacts-credprovider/issues/45#issuecomment-524459207

@shubham90 filed an internal issue to fix this problem. There has not yet been any answer on if the actual issue is fixed. The problem has not been fixed.

**Comment by satbai** [comment]
Our investigation on the internal work item resulted that unfortunately, the way the interactive flow currently works in this cred provider, there is no way to make it work interactively for an on premise Azure DevOps Server instance. The best solution we currently have is to use the workaround of using the environment variables mentioned above. Sorry for the inconvenience.

To make it clearer, the newest version of this cred provider detects if the feed URI is an Azure DevOps Server on premise URI and won't even try the interactive flow to avoid confusing logs.

As a follow-up work item, we should document this in the cred provider readme.

**Comment by Mobrockers** [comment]
Alright thanks.

**Comment by mmulhearn** [comment]
I'm finding that `--interactive` does not work for private packages on Azure Devops, either.

```
PS D:\Dev\sample-func\SampleFunc> dotnet add package --interactive Microsoft.Azure.SignalR.Management
  Determining projects to restore...
  Writing C:\Users\ThisGuy\AppData\Local\Temp\tmpC2A0.tmp
info : Adding PackageReference for package 'Microsoft.Azure.SignalR.Management' into project 'D:\Dev\sample-func\SampleFunc\SampleFunc.csproj'.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.azure.signalr.management/index.json
info :   GET https://pkgs.dev.azure.com/<removed>/_packaging/<removed>/nuget/v3/registrations2-semver2/microsoft.azure.signalr.management/index.json
info :   GET https://<removed>.pkgs.visualstudio.com/_packaging/<removed>/nuget/v3/registrations2-semver2/microsoft.azure.signalr.management/index.json
info :   Unauthorized https://<removed>.pkgs.visualstudio.com/_packaging/<removed>/nuget/v3/registrations2-semver2/microsoft.azure.signalr.management/index.json 272ms
info :   Unauthorized https://pkgs.dev.azure.com/<removed>/_packaging/<removed>/nuget/v3/registrations2-semver2/microsoft.azure.signalr.management/index.json 275ms
error: Response status code does not indicate success: 401 (Unauthorized).
```

I am on `NuGet Command Line 5.8.0.6930` and `dotnet 5.0.1.02`

**Comment by Mobrockers** [comment]
> I'm finding that `--interactive` does not work for private packages on Azure Devops, either.
> 
> ```
> PS D:\Dev\sample-func\SampleFunc> dotnet add package --interactive Microsoft.Azure.SignalR.Management
>   Determining projects to restore...
>   Writing C:\Users\ThisGuy\AppData\Local\Temp\tmpC2A0.tmp
> info : Adding PackageReference for package 'Microsoft.Azure.SignalR.Management' into project 'D:\Dev\sample-func\SampleFunc\SampleFunc.csproj'.
> info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.azure.signalr.management/index.json
> info :   GET https://pkgs.dev.azure.com/<removed>/_packaging/<removed>/nuget/v3/registrations2-semver2/microsoft.azure.signalr.management/index.json
> info :   GET https://<removed>.pkgs.visualstudio.com/_packaging/<removed>/nuget/v3/registrations2-semver2/microsoft.azure.signalr.management/index.json
> info :   Unauthorized https://<removed>.pkgs.visualstudio.com/_packaging/<removed>/nuget/v3/registrations2-semver2/microsoft.azure.signalr.management/index.json 272ms
> info :   Unauthorized https://pkgs.dev.azure.com/<removed>/_packaging/<removed>/nuget/v3/registrations2-semver2/microsoft.azure.signalr.management/index.json 275ms
> error: Response status code does not indicate success: 401 (Unauthorized).
> ```
> 
> I am on `NuGet Command Line 5.8.0.6930` and `dotnet 5.0.1.02`

I suggest you create a new issue as this issue is specific to azure devops server, and has been closed.
